import express from 'express';
import AdminController from '../controllers/AdminController.js';
import { autenticado,perfisPermitidos } from '../middlewares/autorizacao.js';
import { assinc } from '../middlewares/erros.js';

const router=express.Router();const controle=new AdminController();
router.use('/admin',autenticado,perfisPermitidos('administrador'));
router.get('/admin/usuarios',assinc(controle.usuarios));
router.post('/admin/usuarios/:id',assinc(controle.usuario));
router.post('/admin/usuarios/:id/excluir',assinc(controle.delUsuario));
router.get('/admin/cursos',assinc(controle.cursos));
router.post('/admin/cursos',assinc(controle.addCurso));
router.post('/admin/cursos/:id',assinc(controle.edtCurso));
router.post('/admin/cursos/:id/excluir',assinc(controle.delCurso));
router.post('/admin/turmas',assinc(controle.addTurma));
router.post('/admin/turmas/:id',assinc(controle.edtTurma));
router.post('/admin/turmas/:id/excluir',assinc(controle.delTurma));
router.get('/admin/modulos',assinc(controle.modulos));
router.post('/admin/modulos',assinc(controle.addModulo));
router.post('/admin/modulos/:id',assinc(controle.edtModulo));
router.post('/admin/modulos/:id/excluir',assinc(controle.delModulo));
router.get('/admin/denuncias',assinc(controle.denuncias));
router.post('/admin/denuncias/:id',assinc(controle.denuncia));
router.post('/admin/denuncias/:id/excluir',assinc(controle.delDenuncia));
router.get('/admin/configuracao',assinc(controle.configuracao));
router.post('/admin/configuracao',assinc(controle.salvarConfiguracao));
export default router;
