import Ideia, { STATUS_IDEIA } from '../models/ideia.js';
import Comentario from '../models/comentario.js';
import Curso from '../models/curso.js';
import Tcc from '../models/tcc.js';
import { ehDono, lista, podeModerar, regexSegura } from '../utils/texto.js';

export default class IdeiaController {
  constructor(caminhoBase='ideia/'){ this.caminhoBase=caminhoBase; }
  list = async (req,res) => { const {q='',curso='',area='',dificuldade='',status='',ordem='recentes'}=req.query; const filtro={}; if(q){const busca=new RegExp(regexSegura(q),'i');filtro.$or=[{titulo:busca},{descricao:busca},{problema:busca}];} if(curso)filtro.curso=curso;if(area)filtro.area=area;if(dificuldade)filtro.dificuldade=dificuldade;if(status)filtro.status=status; const ideias=await Ideia.find(filtro).populate('curso autor tccVinculado').sort(ordem==='antigas'?{createdAt:1}:{createdAt:-1}); const [cursos,areas]=await Promise.all([Curso.find({ativo:true}),Ideia.distinct('area')]); res.render(this.caminhoBase+'lst',{title:'Banco de Ideias',ideias,cursos,areas,statusIdeia:STATUS_IDEIA,query:req.query}); };
  detalhes = async (req,res) => { const ideia=await Ideia.findById(req.params.id).populate('curso autor tccVinculado'); if(!ideia)return res.status(404).render('404',{title:'Ideia não encontrada'}); const comentarios=await Comentario.find({ideia:ideia.id,oculto:false}).populate('autor').sort({createdAt:1}); res.render(this.caminhoBase+'detalhes',{title:ideia.titulo,ideia,comentarios}); };
  openAdd = async(req,res)=>res.render(this.caminhoBase+'add',{title:'Publicar ideia',cursos:await Curso.find({ativo:true})});
  add = async(req,res)=>{const ideia=await Ideia.create({titulo:req.body.titulo,descricao:req.body.descricao,problema:req.body.problema,curso:req.body.curso,area:req.body.area,dificuldade:req.body.dificuldade,conhecimentos:lista(req.body.conhecimentos),autor:req.session.usuario.id});req.flash('sucesso','Ideia publicada.');res.redirect('/ideias/'+ideia.id);};
  openEdt = async(req,res)=>{const ideia=await Ideia.findById(req.params.id);if(!ideia||(!ehDono(ideia.autor,req.session.usuario)&&!podeModerar(req.session.usuario)))throw Object.assign(new Error('Acesso negado.'),{status:403});res.render(this.caminhoBase+'edt',{title:'Editar ideia',ideia,cursos:await Curso.find({ativo:true}),tccs:await Tcc.find({status:'Publicado'}).select('titulo')});};
  edt = async(req,res)=>{const ideia=await Ideia.findById(req.params.id);if(!ideia)throw new Error('Ideia não encontrada.');const moderador=podeModerar(req.session.usuario);if(!moderador&&(!ehDono(ideia.autor,req.session.usuario)||ideia.status!=='Disponível'))throw Object.assign(new Error('Esta ideia não pode ser editada.'),{status:403});Object.assign(ideia,{titulo:req.body.titulo,descricao:req.body.descricao,problema:req.body.problema,curso:req.body.curso,area:req.body.area,dificuldade:req.body.dificuldade,conhecimentos:lista(req.body.conhecimentos)});if(moderador&&STATUS_IDEIA.includes(req.body.status)){ideia.status=req.body.status;ideia.tccVinculado=req.body.tccVinculado||undefined;ideia.moderada=true;}await ideia.save();req.flash('sucesso','Ideia atualizada.');res.redirect('/ideias/'+ideia.id);};
  del = async(req,res)=>{const ideia=await Ideia.findById(req.params.id);if(!ideia||(!ehDono(ideia.autor,req.session.usuario)&&req.session.usuario.perfil!=='administrador'))throw Object.assign(new Error('Acesso negado.'),{status:403});if(req.session.usuario.perfil!=='administrador'&&ideia.status!=='Disponível')throw new Error('Somente ideias disponíveis podem ser excluídas.');await Comentario.deleteMany({ideia:ideia.id});await ideia.deleteOne();req.flash('sucesso','Ideia excluída.');res.redirect('/ideias');};
  favorito = async(req,res)=>{const Usuario=(await import('../models/usuario.js')).default;const usuario=await Usuario.findById(req.session.usuario.id);const tem=usuario.favoritosIdeia.some(id=>String(id)===req.params.id);await Usuario.findByIdAndUpdate(usuario.id,tem?{$pull:{favoritosIdeia:req.params.id}}:{$addToSet:{favoritosIdeia:req.params.id}});req.flash('sucesso',tem?'Ideia removida dos favoritos.':'Ideia salva nos favoritos.');res.redirect(req.get('referer')||'/ideias');};
}
