import Usuario from '../models/usuario.js';
import Tcc from '../models/tcc.js';
import Ideia from '../models/ideia.js';
import Comentario from '../models/comentario.js';
import Denuncia from '../models/denuncia.js';

export default class PainelController {
  index = async(req,res)=>{const usuario=req.session.usuario;let dados={};if(usuario.perfil==='aluno'){const conta=await Usuario.findById(usuario.id).populate('favoritosTcc favoritosIdeia progressoModulos');dados={tccsEnviados:await Tcc.countDocuments({alunoResponsavel:usuario.id}),correcoesSolicitadas:await Tcc.countDocuments({alunoResponsavel:usuario.id,status:'Correções solicitadas'}),ideiasPublicadas:await Ideia.countDocuments({autor:usuario.id}),favoritos:(conta?.favoritosTcc.length||0)+(conta?.favoritosIdeia.length||0),modulosConcluidos:conta?.progressoModulos.length||0};}else if(usuario.perfil==='professor'){dados={aguardandoRevisao:await Tcc.countDocuments({orientador:usuario.id,status:{$in:['Enviado','Reenviado','Aguardando revisão']}}),aguardandoLiberacao:await Tcc.countDocuments({orientador:usuario.id,status:'Aprovado'}),trabalhosAvaliados:await Tcc.countDocuments({orientador:usuario.id,status:{$in:['Correções solicitadas','Aprovado','Publicado']}}),trabalhosOrientados:await Tcc.countDocuments({orientador:usuario.id}),ideiasEmAnalise:await Ideia.countDocuments({status:'Em análise'}),denunciasPendentes:await Denuncia.countDocuments({status:'Pendente'})};}else{const downloads=await Tcc.aggregate([{$group:{_id:null,total:{$sum:'$downloads'}}}]);dados={totalUsuarios:await Usuario.countDocuments(),totalTccs:await Tcc.countDocuments(),aguardandoAprovacao:await Tcc.countDocuments({status:{$in:['Enviado','Reenviado','Aguardando revisão']}}),aguardandoLiberacao:await Tcc.countDocuments({status:'Aprovado'}),publicados:await Tcc.countDocuments({status:'Publicado'}),totalDownloads:downloads[0]?.total||0,totalIdeias:await Ideia.countDocuments(),denunciasPendentes:await Denuncia.countDocuments({status:'Pendente'}),comentarios:await Comentario.countDocuments()};}res.render('painel/index',{title:'Meu painel',dados});};
  favoritoTcc = async(req,res)=>{const usuario=await Usuario.findById(req.session.usuario.id);const tem=usuario.favoritosTcc.some(id=>String(id)===req.params.id);await Usuario.findByIdAndUpdate(usuario.id,tem?{$pull:{favoritosTcc:req.params.id}}:{$addToSet:{favoritosTcc:req.params.id}});req.flash('sucesso',tem?'TCC removido dos favoritos.':'TCC salvo nos favoritos.');res.redirect(req.get('referer')||'/tccs/'+req.params.id);};
}
